# Generated by Django 2.0.4 on 2018-05-22 05:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floor_plan', '0002_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Pablo',
        ),
    ]
