# Generated by Django 2.0.4 on 2018-05-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plan', '0003_auto_20180522_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pablo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pablo',
        ),
    ]
