# Generated by Django 2.0.4 on 2018-05-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plan', '0004_auto_20180522_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wayan',
            new_name='Participant',
        ),
    ]
