# Generated by Django 2.0.4 on 2018-05-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('length_x', models.IntegerField()),
                ('length_y', models.IntegerField()),
                ('illuminance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.IntegerField()),
                ('length', models.IntegerField()),
                ('side', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('logged_in', models.BooleanField(default=False)),
                ('survey_done', models.BooleanField(default=False)),
                ('room', models.IntegerField()),
                ('desk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
                ('x_length', models.IntegerField()),
                ('y_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.IntegerField()),
                ('length', models.IntegerField()),
                ('side', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floorPlan.Room')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floorPlan.Room'),
        ),
        migrations.AddField(
            model_name='desk',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floorPlan.Room'),
        ),
        migrations.AddField(
            model_name='chair',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floorPlan.Desk'),
        ),
    ]
