# Generated by Django 2.0.4 on 2018-05-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
