# Generated by Django 2.0.4 on 2018-05-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorPlan', '0002_auto_20180503_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='table_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='code',
        ),
    ]
