# Generated by Django 2.0.4 on 2018-05-17 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floorPlan', '0004_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='chair',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chair',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='x_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='y_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='x_pos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='x_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_pos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='end_pos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='window',
            name='start_pos',
            field=models.IntegerField(),
        ),
    ]
