# Generated by Django 2.0.4 on 2018-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorPlan', '0005_auto_20180517_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email_address',
            field=models.CharField(default='231', max_length=250, unique=True),
        ),
    ]
