# Generated by Django 2.0.4 on 2018-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorPlan', '0006_participant_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email_address',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
