# Generated by Django 2.0.4 on 2018-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorPlan', '0007_auto_20180517_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wayan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('loggedIn', models.BooleanField(default=False)),
            ],
        ),
    ]
